---
# tasks file for postgresql

- name: Install dependencies for PostgreSQL
  apt:
    name: ['python3-psycopg2', "acl"]
    update_cache: true state=latest

- name: Install PostgreSQL
  apt: name=postgresql update_cache=true state=present

- name: start postgresql
  service: name=postgresql state=started enabled=yes

- name: Create the database specified in vars
  become_user: postgres
  postgresql_db: name={{ db_name }} template='template0' state=present

- name: Ensure user has access to the new database
  become_user: postgres
  postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_password }} priv=ALL state=present

- name: Allow md5 connection for the db user
  become_user: postgres
  postgresql_pg_hba:
    dest="{{ path }}/pg_hba.conf" contype=host databases=all method=md5 users=all create=true source=0.0.0.0/0

- name: Replace a localhost entry with our own
  lineinfile:
    path={{ path }}/postgresql.conf  regexp="#listen_addresses = 'localhost'"  line=listen_addresses='*'

- name: restart service postgresql
  service: name=postgresql state=restarted