---
# tasks file for amazon_docker_tomcat
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_only: yes

- name: Ensure a list of yum packages are installed
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python-pip
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - amazon-linux-extras

- name: Add extras repository
  shell: yum-config-manager --enable extras

- name: Install docker-ce (centos) via amazon-linux-extras packages
  shell: "amazon-linux-extras install docker -y"

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes

- name: Adding user '{{ user }}' to docker group  
  user: 
    name: '{{ user }}'
    group: docker
    append: yes