---
# tasks file for amazon_docker_tomcat
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_only: yes

- name: Ensure a list of yum packages are installed
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python-pip
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - amazon-linux-extras
    - git
- name: Install docker module for python
  pip:
    name: ["docker-py","psutil","statsd"]

- name: Add extras repository
  shell: yum-config-manager --enable extras

- name: Install docker-ce (centos) via amazon-linux-extras packages
  shell: "amazon-linux-extras install docker -y"

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes

- name: Adding user ec2-user to docker group  
  user: 
    name: ec2-user
    groups: docker
    append: yes
  become: yes

- name: Allow access to insecure registry
  template:
    src: daemon.j2
    dest: /etc/docker/daemon.json
  notify: 
  - Reload docker

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
  
- name: Log into private registry and force re-authorization
  docker_login:
    registry: "http://{{ nexus_url }}/repository/d4m-docker-images/"
    username: "{{ nexus_admin }}"
    password: "{{ nexus_pass }}"
    reauthorize: yes

- name: Create a geocitizen container
  docker_container:
    name: geocitizen
    image: "{{ nexus_url }}/repository/d4m-docker-images/tomcat-geo:latest"
    ports:
      - "8080:8080"

#statsd daemon docker
- name: Clone statsd from github
  git:
    repo: https://github.com/statsd/statsd.git
    dest: ./statsd
    clone: yes
    force: yes

- name: Change graphite url
  replace:
    path: ./statsd/Dockerfile
    regexp: 'graphite\.example\.com'
    replace: "{{ graphite_url }}"

- name: Build statsd image
  docker_image:
    build:
      path: ./statsd
    name: statsd
    tag: latest
    source: build

- name: Create a geocitizen container
  docker_container:
    name: statsd
    image: "statsd:latest"
    ports:
      - "8125:8125/udp"

#statsd-agent python script
- name: Clone statsd-agent from github
  git:
    repo: https://github.com/blackrosezy/statsd-agent.git
    dest: ./statsd-agent
    clone: yes
    force: yes

- name: Copy a "statsd-agent.py" to /opt
  ansible.builtin.copy:
    src: ./statsd-agent/statsd-agent.py
    dest: /opt
    remote_src: yes

- name: create supervisor app
  template:
    src: statsd-agent.j2
    dest: /etc/supervisor/conf.d/statsd-agent.conf

- name: start and enable supervisor
  service:
    name: supervisor
    state: restarted
    enable: true

#sensugo client