- name: Playbook to copy citizen.war to tomcat server and restart tomcat.
  hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - name: copy citizen.war
      copy:
        src: citizen.war
        dest: /opt/tomcat/webapps/
    - name: reload tomcat
      service:
        name: tomcat
        state: restarted
    - name: NOW YOU CAN USE GEOCITIZEN
      debug:
        msg: "http://{{ ansible_ssh_host }}:8080//citizen" 
