---
- name: Deploy a web application
  hosts: all
  become: yes

  roles:
    - { role: postgresql, when: ansible_distribution == 'Ubuntu' }
    - { role: tomcat, when: ansible_distribution == 'Amazon' }