# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  //backend "s3" {}
  required_providers {
    aws = "3.62.0"
    google = "3.87.0"
  }
  required_version = "1.0.7"
}
provider "aws" {
  region = "eu-north-1"
}
provider "google" {
  //project = var.gcp_project
}
