---
- name: Log into private registry and force re-authorization
  docker_login:
    registry_url: "{{ nexus_url }}"
    username: "{{ nexus_usr }}"
    password: "{{ nexus_pass }}"
    reauthorize: yes

- name: Start container from image on Nexus Repository
  docker_container:
    name: "{{ container_name }}"
    image: "{{ nexus_url }}{{ img_name }}:{{ img_tag }}"
    state: started
    detach: yes
    ports:
      # Publish container port 8080 as host port 8080
      - "8080:8080"
