---
# vars file for gke

gcp_project       : test-and-mon
gcp_zone          : europe-west2-c 
cluster_name      : test2-and-mon
initial_node_count: 3
gcp_cred_file     : vault/test-and-mon-83fb16087f3a.json
cluster_state     : present # absent
# namespace_state   : present # absent 
# deploy_sonar_state: present # absent
# deploy_posgr_state: present # absent
# postgres_password : $POSTGRES_PASSWORD
# pv_state          : present # absent
# pvc_state         : present # absent
# svc_sonar_state   : present # absent
# svc_postgr_state  : present # absent