---
# tasks file for pull_image
- name: Install docker module for python
  pip:
    # executable: pip3
    name: docker-py #docker==4.4.4

# - name: Upgrade pip3
#   shell: "python3.8 -m pip install docker==4.4.4"    

- name: Log into private registry and force re-authorization
  docker_login:
    registry: 34.107.30.34:8077
    username: admin
    password: r,j,dnexus
    reauthorize: yes

- name: Load image from archive and push to a private registry
  docker_image:
#     repository: 34.107.30.34:8077/tomcat_sv 
#     name: 34.107.30.34:8077/tomcat_sv
    tag: v1.74
    pull: yes