---
# tasks file for pull_image
- name: run container
    docker_image:
      insecure_registry: true
      image: 34.107.30.34:8077/tomcat_sv
      state: reloaded
      pull: always
      ports:
       - "8080:8080"

# - name: Load image from archive and push to a private registry
#   docker_image:
#     repository: 34.107.30.34:8077/tomcat_sv 
#     name: 34.107.30.34:8077/tomcat_sv
#     tag: v1.74
#     push: yes