---
# tasks for ContainerizeGeo role
- name: Ensure andre o/s group exists
  group:
    name: andre
    state: present

- name: Create a directory if it does not exist
  file:
    path: "{{ geo_path }}"
    state: directory
    owner: andre
    group: andre
    mode: "0744"

- name: Copying Dockerfile, citizen.war, context.xml file
  copy:
    src: "{{ item }}"
    dest: "{{ geo_path }}"
    owner: andre
    group: andre
    mode: "0644"
  loop: "{{ copy_files }}"

- name: "Template a daemon.json file to {{ daemon_path }}"
  template:
    src: daemon.json.j2
    dest: "{{ daemon_path }}/daemon.json"
    mode: "0644"

- name: Restart service Docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Log into private registry and force re-authorization
  docker_login:
    registry_url: "{{ nexus_url }}"
    username: "{{ nexus_usr }}"
    password: "{{ nexus_pass }}"
    reauthorize: yes

- name: Build an Docker image and push it to a private Nexus repo
  docker_image:
    build:
      path: "{{ geo_path }}"
    name: "{{ nexus_url }}{{ img_name }}:{{ tag_name }}"
    tag: "{{ tag_name }}"
    push: yes
    source: build
