---
# tasks file for ws

- name: install java
  yum: name=java-1.8.0-openjdk-devel state=present

- name: create group
  group: name=tomcat state=present

- name: create user
  user: name=tomcat group=tomcat home=/opt/tomcat shell=/bin/false

- name: unarchive file
  unarchive:
    src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
    dest: /opt/tomcat/
    remote_src: True

- name: create a symbolic link
  file: src=/opt/tomcat/apache-tomcat-9.0.54 dest=/opt/tomcat/latest state=link

- name: chown for tomcat folder
  file: path=/opt/tomcat owner=tomcat group=tomcat recurse=yes

- name: chmod for tomcat folder "conf" read
  file: path=/opt/tomcat/latest/conf owner=tomcat group=tomcat mode=g+r recurse=yes

- name: chmod for tomcat folder "conf" execute
  file: path=/opt/tomcat/latest/conf owner=tomcat group=tomcat mode=g+x

- name: copying "tomcat.servise" file
  copy: src=tomcat.service dest=/etc/systemd/system/
  notify: 
  - restart daemons
  - restart tomcat service
