---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamlint .
platforms:
  - name: instance
    image: ubuntu:20.04
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
