FROM tomcat:9.0.53-jre8-openjdk-slim-buster

COPY context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml
COPY context.xml /usr/local/tomcat/webapps/host-manager/META-INF/context.xml
COPY citizen.war /usr/local/tomcat/webapps/