FROM tomcat:9.0.53-jre8-openjdk-slim-buster

ADD context.xml /usr/local/tomcat/webapps/manager/META-INF/
ADD context.xml /usr/local/tomcat/webapps/host-manager/META-INF/
ADD citizen.war /usr/local/tomcat/webapps/