---
# tasks file for ubuntu_psql_db
- name: apt update
  apt:
    update_cache: yes
- name: install dependencies
  apt:
    name: ['python3-psycopg2', 'acl']
    state: present
- name: add key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
- name: add repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
    state: present
- name: Update the repository cache and install postgresql-11
  apt:
    name: postgresql-11
    state: present
    update_cache: yes
- name: Enable postgresql service
  service:
    name: postgresql
    state: started
    enabled: yes
- name: Create database
  become_user: postgres
  postgresql_db:
    name: ss_demo_1
    state: present
- name : Grant permissions
  become_user: postgres
  postgresql_user:
    db: ss_demo_1
    name: postgres
    password: postgres
    priv: ALL
    state: present
- name: Allow md5 connection for the db user
  become_user: postgres
  postgresql_pg_hba:
    dest: /etc/postgresql/11/main/pg_hba.conf 
    contype: host 
    databases: all
    method: md5
    users: all
    create: true
    source: 0.0.0.0/0
  notify: Restart Postgres
- name: allow every host connect to database
  lineinfile:
    path: /etc/postgresql/11/main/postgresql.conf
    regexp: "^#listen_addresses = 'localhost'"
    line: listen_addresses='*'
  notify: Restart Postgres